repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.5
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.30.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "5.2"]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.48.0
  hooks:
  - id: markdownlint
    exclude: |
      (?x)^(
        ISSUE_TEMPLATE\.md
      )
- repo: https://github.com/thlorenz/doctoc
  rev: v2.3.0
  hooks:
  - id: doctoc
    files: |
      (?x)^(
        (CONTRIBUTING|SECURITY).*\.md|
        install/README\.md
      )
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
  - id: mypy
    additional_dependencies:
    # Most of these dependencies are necessary because django-stubs initializes
    # Django's runtime to extract information about the models.
    - agentarchives
    - bagit
    - boto3
    - django-auth-ldap
    - django-cas-ng
    - django-stubs-ext
    - django-stubs[compatible-mypy]
    - django-tastypie
    - jsonfield
    - metsrw
    - prometheus-client
    - pytest
    - python-gnupg
    - python-swiftclient
    - sword2 @ git+https://github.com/artefactual-labs/python-client-sword2.git@619ee44467dcdb2ab75fab16864ea2e4ded7ffe4
    - types-requests
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.14.2
  hooks:
  - id: markdown-link-check
    stages: [manual]
    args: [--quiet, --config, .markdown-link-check.json]
