repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: pretty-format-json
    args: [--no-ensure-ascii, --autofix]
    files: |
      (?x)^(
        osdeps/.*\.json
      )
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    args: [--py38-plus]
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.16.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "4.2"]
- repo: https://github.com/psf/black
  rev: "23.12.1"
  hooks:
  - id: black
    args: [--safe, --quiet]
- repo: https://github.com/pycqa/flake8
  rev: "7.0.0"
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear==23.9.16
    - flake8-comprehensions==3.14.0
    exclude: |
      (?x)^(
        storage_service/storage_service/settings/.*\.py
      )
- repo: https://github.com/pycqa/flake8
  # This is a temporary hook to port os.path code to pathlib gradually. Add
  # the ported modules/packages explicitly to `files` below. For reference see
  # https://github.com/archivematica/Issues/issues/1622#issuecomment-1912524642
  rev: "7.0.0"
  hooks:
  - id: flake8
    name: flake8-use-pathlib
    args: [--select, "PL"]
    additional_dependencies:
    - flake8-use-pathlib==0.3.0
    files: |
      (?x)^(
        storage_service/storage_service/settings/.*\.py |
        storage_service/common/gpgutils.py |
        storage_service/common/startup.py |
        storage_service/common/management/commands/populate_aip_checksums.py |
        storage_service/common/management/commands/import_aip.py
      )
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
  - id: eslint
    files: ^storage_service/static/js/(project|.*directory_picker|file-explorer).js
    args: [--fix]
    additional_dependencies:
    - eslint@8.56.0
    - eslint-config-prettier@9.1.0
    - eslint-plugin-prettier@5.1.3
    - prettier@3.0.3
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint
    exclude: |
      (?x)^(
        ISSUE_TEMPLATE\.md
      )
- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
  - id: doctoc
    files: |
      (?x)^(
        (CONTRIBUTING|SECURITY).*\.md|
        install/README\.md
      )
