repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-json
    args: [--no-ensure-ascii, --autofix]
    files: |
      (?x)^(
        osdeps/.*\.json
      )
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus, --py36-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus, --py36-plus]
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.14.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "3.2"]
- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: 'v7.21.0'
  hooks:
  - id: eslint
    files: ^storage_service/static/js/(project|.*directory_picker|file-explorer).js
    args: [--fix]
    additional_dependencies:
    - eslint@7.22.0
    - eslint-config-prettier@8.1.0
    - eslint-plugin-prettier@3.3.1
    - prettier@2.2.1
