repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.18.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "4.2"]
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
  - id: eslint
    files: ^storage_service/static/js/(project|.*directory_picker|file-explorer).js
    args: [--fix]
    additional_dependencies:
    - eslint@8.56.0
    - eslint-config-prettier@9.1.0
    - eslint-plugin-prettier@5.1.3
    - prettier@3.0.3
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    exclude: |
      (?x)^(
        ISSUE_TEMPLATE\.md
      )
- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
  - id: doctoc
    files: |
      (?x)^(
        (CONTRIBUTING|SECURITY).*\.md|
        install/README\.md
      )
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
    - types-python-dateutil
