[lint]
# Rule reference: https://docs.astral.sh/ruff/rules/
select = [
  "B",
  "C4",
  "E",
  "F",
  "I",
  "PTH",
  "UP",
  "W",
]
ignore = [
  "B904",
  "E501",
  "UP031",
]

[lint.per-file-ignores]
"{storage_service,tests}/locations/*" = ["PTH"]

[lint.isort]
force-single-line = true
