[lint]
# Rule reference: https://docs.astral.sh/ruff/rules/
select = [
  "B",
  "C4",
  "E",
  "F",
  "I",
  "PTH",
  "UP",
  "W",
]
ignore = [
  "B904",
  "E501",
  "UP031",
]

[lint.per-file-ignores]
"{storage_service,tests}/locations/*" = ["PTH"]
"storage_service/storage_service/settings/*" = [
  "F403",
  "F405",
]
"storage_service/storage_service/settings/base.py" = ["E402"]

[lint.isort]
force-single-line = true
