# Generated by Django 1.11.29 on 2023-07-26 15:25
import uuid

from django.db import migrations

from archivematica.storage_service.common.fields import UUIDField


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0033_package_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callback",
            name="uuid",
            field=UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="file",
            name="origin",
            field=UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier of originating Archivematica dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="packagedownloadtask",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="packagedownloadtaskfile",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pipeline",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                help_text="Identifier for the Archivematica pipeline",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="uuid",
            field=UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier",
                unique=True,
            ),
        ),
    ]
