#archivematica-storage-service.install

# TODO: Add upstart/systemd script with gunicorn
#	and update nginx config
install/storage.ini etc/uwsgi/apps-available/
install/storage etc/nginx/sites-available/
install/.storage-service var/archivematica/
install/make_key.py var/archivematica/storage-service/

lib/* var/archivematica/storage-service/lib/
storage_service/* usr/lib/archivematica/storage-service/
