#archivematica-storage-service.install

install/storage.ini etc/uwsgi/apps-available/
install/storage etc/nginx/sites-available/
install/.storage-service var/archivematica/
install/make_key.py var/archivematica/storage-service/

lib/* var/archivematica/storage-service/lib/

storage_service/static/* /var/archivematica/storage-service/static/
storage_service/templates/* /var/archivematica/storage-service/templates/
