#!/bin/bash

#postrm 
#run after the package is uninstalled

echo "postrm" $1
if [ $1 = "remove" ]; then
    #clean up storage service directories
    rm -rf /usr/share/python/archivematica-storage-service
    rm -rf /var/archivematica/storage*
    rm -r /var/archivematica/.storage-service
    rm -f /tmp/storage_service.log
    rm -f /etc/nginx/sites-enabled/storage
    rm -f /etc/nginx/sites-available/storage
    rm -f /etc/uwsgi/apps-enabled/storage.ini
    rm -f /etc/uwsgi/apps-available/storage.ini
    rm -rf /usr/lib/archivematica/storage*

fi

exit 0

#DEBHELPER#

