#!/bin/sh

echo "creating archivematica user"
userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi


echo "creating django secret key"
KEYCMD=$(python /var/archivematica/storage-service/make_key.py 2>&1)
echo $KEYCMD

sed -i "s/<replace-with-key>/\"$KEYCMD\"/g" /var/archivematica/.storage-service
sed -i "s/<replace-with-key>/\"$KEYCMD\"/g" /etc/uwsgi/apps-available/storage.ini

. /var/archivematica/.storage-service

echo "creating symlink in /usr/lib/archivematica"
rm -f /usr/lib/archivematica/storage-service
ln -s -f /usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/storage_service/ /usr/lib/archivematica/storage-service
rsync -a /var/archivematica/storage-service/static /usr/lib/archivematica/storage-service
rsync -a /var/archivematica/storage-service/templates /usr/lib/archivematica/storage-service

cd /usr/lib/archivematica/storage-service

echo "installing swift dependencies"
/usr/share/python/archivematica-storage-service/bin/pip install python-swiftclient
/usr/share/python/archivematica-storage-service/bin/pip install python-keystoneclient

echo "configuring django database and static files"
/usr/share/python/archivematica-storage-service/bin/python manage.py syncdb
/usr/share/python/archivematica-storage-service/bin/python manage.py migrate
/usr/share/python/archivematica-storage-service/bin/python manage.py collectstatic --noinput

echo "create /var/archivematica/storage_service directory"
mkdir -p /var/archivematica/storage_service

echo "updating directory permissions"
chown -R archivematica:archivematica /var/archivematica/storage-service
chown -R archivematica:archivematica /var/archivematica/storage_service
chown -R archivematica:archivematica /var/archivematica/.storage-service
chown -R archivematica:archivematica /usr/share/python/archivematica-storage-service
chown -R archivematica:archivematica /var/log/archivematica/storage-service

rm -f /tmp/storage_service.log

#DEBHELPER#
