#!/bin/sh

echo "creating archivematica user"
userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi


echo "creating django secret key"
KEYCMD=$(python /var/lib/archivematica/make_key.py 2>&1)
echo $KEYCMD

sed -i "s/<replace-with-key>/\"$KEYCMD\"/g" /var/lib/archivematica/.storage-service
sed -i "s/<replace-with-key>/\"$KEYCMD\"/g" /etc/uwsgi/apps-available/storage.ini

. /var/lib/archivematica/.storage-service

echo "creating symlink in /usr/lib/archivematica"
ln -s /usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/archivematica_storage_service-0.2.2-py2.7.egg/storage_service/ /usr/lib/archivematica/storage-service
mv /var/archivematica/storage-service/static /usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/archivematica_storage_service-0.2.2-py2.7.egg/storage_service/static
mv /var/archivematica/storage-service/templates /usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/archivematica_storage_service-0.2.2-py2.7.egg/storage_service/templates

echo "configuring django database and static files"
cd /usr/lib/archivematica/storage-service

/usr/share/python/archivematica-storage-service/bin/python manage.py syncdb
/usr/share/python/archivematica-storage-service/bin/python manage.py collectstatic --noinput

echo "updating directory permissions"
chown -R archivematica:archivematica /var/archivematica/
chown -R archivematica:archivematica /usr/share/python/archivematica-storage-service

rm /tmp/storage-service.log
