#!/bin/bash

echo "postinst called with:" $1 $2

echo "creating archivematica user"
userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi


echo "creating django secret key"
KEYCMD=$(python /var/archivematica/storage-service/make_key.py 2>&1)
echo $KEYCMD

sed -i "s/<replace-with-key>/\"$KEYCMD\"/g" /var/archivematica/.storage-service
sed -i "s/<replace-with-key>/\"$KEYCMD\"/g" /etc/uwsgi/apps-available/storage.ini

. /var/archivematica/.storage-service

cd /usr/lib/archivematica/storage-service

echo "configuring django database and static files"
find /usr/lib/archivematica/storage-service/ -name '*.pyc'  -delete
# 0.3.0 will automatically fake the first migration
if [[ $2 == '0.7.'* || $2 == '0.6.'* || $2 == '0.5.'* || $2 == '0.4.'* ]]; then
    echo 'Faking the 0.4 migration'
    /usr/share/python/archivematica-storage-service/bin/python manage.py migrate locations 0002_v0_4 --fake
fi
if [[ $2 == '0.7.'* || $2 == '0.6.'* || $2 == '0.5.'* ]]; then
    echo 'Faking 0.5 migration'
    /usr/share/python/archivematica-storage-service/bin/python manage.py migrate locations 0003_v0_5 --fake
fi

if [[ $2 == '0.7.'* || $2 == '0.6.'* ]]; then
    echo 'No migrations in 0.6'
fi

if [[ $2 == '0.7.'* ]]; then
    echo 'Faking 0.7 migration'
    /usr/share/python/archivematica-storage-service/bin/python manage.py migrate locations 0004_v0_7 --fake
fi

/usr/share/python/archivematica-storage-service/bin/python manage.py migrate --fake-initial
/usr/share/python/archivematica-storage-service/bin/python manage.py collectstatic --noinput


echo "updating directory permissions"
chown -R archivematica:archivematica /var/archivematica/storage-service
chown -R archivematica:archivematica /var/archivematica/storage_service
chown -R archivematica:archivematica /var/archivematica/.storage-service
chown -R archivematica:archivematica /usr/share/python/archivematica-storage-service
chown -R archivematica:archivematica /var/log/archivematica/storage-service

rm -f /tmp/storage_service.log

#DEBHELPER#
