# Generated by Django 1.11.29 on 2020-12-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("locations", "0025_update_package_size")]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    (b"PENDING", "Upload Pending"),
                    (b"STAGING", "Staged on Storage Service"),
                    (b"UPLOADED", "Uploaded"),
                    (b"VERIFIED", "Verified"),
                    (b"FAIL", "Failed"),
                    (b"DEL_REQ", "Delete requested"),
                    (b"DELETED", "Deleted"),
                    (b"FINALIZE", "Deposit Finalized"),
                    (b"MOVING", "Moving"),
                    (b"RECOVER_REQ", "Recover requested"),
                ],
                default=b"FAIL",
                help_text="Status of the package in the storage service.",
                max_length=11,
            ),
        )
    ]
