# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-30 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0029_python3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "permissions": [
                    (
                        "approve_package_deletion",
                        "Can approve Package deletion requests",
                    )
                ],
                "verbose_name": "Package",
            },
        ),
    ]
