# Generated by Django 2.2.24 on 2021-07-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0029_python3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dspacerest",
            name="upload_to_tsm",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If checked, will attempt to send the AIP to the Tivoli Storage Manager using command-line client dsmc, which must be installed manually",
                verbose_name="Send AIP to Tivoli Storage Manager?",
            ),
        ),
        migrations.AlterField(
            model_name="dspacerest",
            name="verify_ssl",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="If checked, HTTPS requests will verify the SSL certificates",
                verbose_name="Verify SSL certificates?",
            ),
        ),
        migrations.AlterField(
            model_name="lockssomatic",
            name="keep_local",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="If checked, keep a local copy even after the AIP is stored in the LOCKSS network.",
                verbose_name="Keep local copy?",
            ),
        ),
    ]
