# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0031_rclone_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="stored_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Datetime when package is successfully stored",
                null=True,
            ),
        ),
    ]
