# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0032_package_stored_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="checksum",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="checksum_algorithm",
            field=models.TextField(blank=True, default="sha256", null=True),
        ),
    ]
