# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0033_package_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archipelago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archipelago_url', models.URLField(help_text='Archipelago URL', max_length=256, verbose_name='Archipelago URL')),
                ('archipelago_user', models.CharField(help_text='Archiipelago username for authentication', max_length=64, verbose_name='Archipelago username')),
                ('archipelago_password', models.CharField(help_text='Archipelago password for authentication', max_length=64, verbose_name='Archipelago password')),
            ],
            options={
                'verbose_name': 'Archipelago via REST API',
            },
        ),
        migrations.AlterField(
            model_name='space',
            name='access_protocol',
            field=models.CharField(choices=[('ARCHIPEL', 'Archipelago'), ('ARKIVUM', 'Arkivum'), ('DV', 'Dataverse'), ('DC', 'DuraCloud'), ('DSPACE', 'DSpace via SWORD2 API'), ('DSPC_RST', 'DSpace via REST API'), ('FEDORA', 'FEDORA via SWORD2'), ('GPG', 'GPG encryption on Local Filesystem'), ('FS', 'Local Filesystem'), ('LOM', 'LOCKSS-o-matic'), ('NFS', 'NFS'), ('REPLICA', 'Write-Only Replica Staging on Local Filesystem'), ('PIPE_FS', 'Pipeline Local Filesystem'), ('RCLONE', 'RClone'), ('SWIFT', 'Swift'), ('S3', 'S3')], help_text='How the space can be accessed.', max_length=8, verbose_name='Access protocol'),
        ),
        migrations.AddField(
            model_name='archipelago',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.Space', to_field='uuid'),
        ),
    ]
