# Generated by Django 3.2.20 on 2023-07-27 15:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0034_use_uuidfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dspacerest",
            name="upload_to_tsm",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If checked, will attempt to send the AIP to the Tivoli Storage Manager using command-line client dsmc, which must be installed manually",
                verbose_name="Send AIP to Tivoli Storage Manager?",
            ),
        ),
        migrations.AlterField(
            model_name="dspacerest",
            name="verify_ssl",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="If checked, HTTPS requests will verify the SSL certificates",
                verbose_name="Verify SSL certificates?",
            ),
        ),
        migrations.AlterField(
            model_name="fixitylog",
            name="success",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="lockssomatic",
            name="keep_local",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="If checked, keep a local copy even after the AIP is stored in the LOCKSS network.",
                verbose_name="Keep local copy?",
            ),
        ),
    ]
