# Generated by Django 4.2.10 on 2024-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0036_archipelago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='related_packages',
            field=models.ManyToManyField(to='locations.package'),
        ),
    ]
