name: "Push images to Docker Hub"
on: workflow_dispatch
jobs:
  build:
    name: "Builds images and push them to Docker Hub"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: artefactual
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: "Build and Push Storage Service"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          file: ./Dockerfile
          target: "archivematica-storage-service"
          tags: artefactual/archivematica-storage-service:latest
